name: hello-world
on: push
jobs:
  hello-world-job:
     runs-on: windows-latest
     steps:
       - name: Check out repository code
         uses: actions/check out@v3
       - run: echo "$(cat hello_world.txt)" 
